theme: jekyll-theme-slate
title: FuriLibs
description: Knowlegde base for WordPress theming

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

# Outputting
permalink: /post/:title/
paginate: 20
paginate_path: '/page/:num/'
